### ISSUE TITLE
energy buffer 0.0%

### ISSUE THREAD

**Issue by MrJoBe** [erogenousbeef/BigReactors#426]
I just cant get any power..

![buffer](https://cloud.githubusercontent.com/assets/10584155/5792666/e62b727c-9f24-11e4-8b5a-98e1c8a7cfe2.png)

**Comment by erogenousbeef** [comment]
You have coolant ports on your reactor. When coolant ports are present, the reactor is in "active cooling" mode. Two options:

(1) Pipe water into the inlet coolant port and pipe the resulting steam out of the outlet coolant port. This steam can be piped to a BR turbine, TE steam dynamo or any other block which consumes steam.

(2) Remove the coolant ports. The reactor will revert to "passive cooling" mode and generate energy instead of steam.

**Comment by MrJoBe** [comment]
Of corse. Thnx. ( :-B )
Den 18 jan 2015 15:23 skrev "Mr. E. Beef" <notifications@github.com>:
