### ISSUE TITLE
Turbines behave poorly when interior is modified without removing casing

### ISSUE THREAD

**Issue by JoBiden** [erogenousbeef/BigReactors#431]
Using an EnderIO staff of travel (and likely other methods) it is possible to get inside a reactor or turbine without removing any casing. doing so to add coils after the rest of the turbine was constructed, a turbine which should have spun to ~900 rpm spun to an arbitrarily large speed while generating no power. Removing and then replacing a casing appears to fix the issue.

**Comment by erogenousbeef** [comment]
That's intentional and by design.

Turbines and reactors only calculate most of their production-related values when they assemble. This is considerably cheaper than calculating them at runtime - in fact, one of the reasons you have to "seal" a reactor in casing/glass is to **prevent** modifications to reactor/turbine interiors while they're running.

You'll also notice that you don't die (even though you logically should), because I omitted checks to see if there's any entities inside. Normally, that can't happen, so they're unnecessary and are omitted to reduce tick time.

So, basically, don't do that.
