### ISSUE TITLE
Losing power.

### ISSUE THREAD

**Issue by Zanxu** [erogenousbeef/BigReactors#446]
Me and a buddy started a server and i built the simple 3x3 reactor like i usually do for basic stuff. After i built a new 7x7 and hed build one of his own i noticed the 3x3 being unable to hold power, plenty of yellorium and whatnot in it, just slowly reduces ticks til its empty. I'm wondering if there is some limit to the amount of reactors you can have? Cannot seem to find that info anywhere.

**Comment by erogenousbeef** [comment]
There's no limit to the number of reactors you can have. What do you mean by "just slowly reduces ticks"?

Also, please list your Forge version, CoFHCore version, BR version and (ideally) a mod list.

**Comment by simpleimbecile2** [comment]
https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7+1.2.0 all enabled

**Comment by simpleimbecile2** [comment]
On our server the simple 3x3 slowly reduces it's output with no relativity to the heat, and now with 1.2 all the reactors seem to suffer from this degradation

**Comment by moTechPlz** [comment]
<i>plenty of yellorium and whatnot in it</i>

Do you remove the cyanite Ingots from the access port? If they stack up to 64 i guess the the depleted fuel isnt replace with new fuel anymore.

**Comment by erogenousbeef** [comment]
@simpleimbecile2 All reactors will slowly fluctuate in power output due to fuel richness degrading as fuel gets used up. I expect, if you watch the reactor closely, you'll see the output spike back up to maximum when a new fuel ingot gets sucked into the reactor.

I'm still unclear as to what @Zanxu means by "slowly reduces ticks" and "unable to hold power".

**Comment by erogenousbeef** [comment]
No new information after 20 days, closing.
