### ISSUE TITLE
Missing old downloads and contacts

### ISSUE THREAD

**Issue by Mitelin** [erogenousbeef/BigReactors#491]
Your web page missing all old downloads 
Please add links to old downloads.

And dont please ask me why im write here if you dont give any contact it is onli logical to people try any way possible

**Comment by Gunner76th** [comment]
http://www.big-reactors.com/#/download If you visit the official site for Big Reactors, you will find the downloads listed there. Please make sure you check the official MC forums, Official mods page and Wiki in the future.

**Comment by Gunner76th** [comment]
Also, if you do not see a long list of downloads dating back to 1.6.4, make sure you have any ad blockers disabled. I am using chrome with Ad Block and ABP, and I am able to see them all just fine.

**Comment by avere001** [comment]
It appears as though the downloads list only sometimes loads for me. Try refreshing the page until it appears

**Comment by Mitelin** [comment]
0.3.4A2     Yes     1.6.4   9.11.1.953+
Missing versions under 0.3.4A2...... 

So no your donwloads are still missing

**Comment by Gunner76th** [comment]
While I am in no way associated with the author of this mod, I am still curious as to why you would want/need any version of Big Reactors prior to the final release for 1.6.4? Big reactors did not exsist prior to 1.6.4, and the versions prior to the final release were littered with bugs and issues, and this is one reason that even to this day, the mod itself is still in Alpha state as noted by the version release number of 0.4.3A. 

Also, please remember, the mod authors are under no requirement or obligation to provide ANY downloads prior to their most recent release. Most do as either a method of record keeping or courtesy, but there are still many more out there who only make their most recent download publicly available. 

Also, in case you did no notice it, here is the change log for this mod going back to initial release https://github.com/erogenousbeef/BigReactors/blob/master/Changelog.md Do you really want to have to deal with any of the issues that were fixed by updates leading up to release 0.3.4A2? And do you fully understand that you would receive zero support or assistance from anyone if you were to use a version prior to 0.3.4A2, and in fact support for 1.6.4 as far as bugs go has been completely dropped as the author has moved onto working on 1.7.10 builds of his mod.

**Comment by Mitelin** [comment]
Mod did exist from end of 1.4.7 era whit 1.14A 1.4.7 version as lowest 1.4.7 existed.
We did use your server from early years...

And im got question too why dont mod autors know that 70% of actual modpack players are still playing 1.2.5 to 1.5.2 versions..... Is it too hard to beleve ?? then look at donwload graphs on technic site....

So why do im looking for those versions?? because MOST OF PLAYERS STILL PLAY THEM....

**Comment by erogenousbeef-zz** [comment]
Sorry, no, I have no intention of providing versions older than those already on the big-reactors.com website. End of discussion.
